apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::619115920608:role/AmazonEKSLoadBalancerControllerRole"

